spring.application.name=eureka
server.port=8761

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.server.hostname=localhost
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=2000
